services:
  # agent:
  #   image: ghcr.io/matthewtran22/homelab_voice_agent:latest
  #   container_name: voice-agent
  #   restart: unless-stopped

  discord-bot:
    build: ./discord-bot
    container_name: discord-bot
    restart: unless-stopped
    env_file:
      - ./discord-bot/.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./audio-output:/app/audio

  asr-agent:
    build:
      context: .
      dockerfile: ./asr-agent/Dockerfile
    container_name: asr-agent
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "50051:50051"
    volumes:
      - ./audio-output:/app/audio
      - ./asr-agent/audio-tests:/app/audio-tests

  asr-test:
    build:
      context: .
      dockerfile: ./asr-agent/Dockerfile.test
    container_name: asr-test
    depends_on:
      - asr-agent
